// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-6hzUMeWZ0_gL2wNiZ7xjtWn3HWu-Ypw',
    appId: '1:162069967907:web:a0ca818462994c044b6d96',
    messagingSenderId: '162069967907',
    projectId: 'laptrinhdidongcuoikyv2-8133a',
    authDomain: 'laptrinhdidongcuoikyv2-8133a.firebaseapp.com',
    storageBucket: 'laptrinhdidongcuoikyv2-8133a.firebasestorage.app',
    measurementId: 'G-E105CXB4EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ83Uold36mSOR5XdRWcujJpOb75PIw1g',
    appId: '1:162069967907:android:4d6cd2c0fd61b0a04b6d96',
    messagingSenderId: '162069967907',
    projectId: 'laptrinhdidongcuoikyv2-8133a',
    storageBucket: 'laptrinhdidongcuoikyv2-8133a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL3ergOh4lijYuomCfDqfP28i4ZnNUDuY',
    appId: '1:162069967907:ios:8c9c76523909fde74b6d96',
    messagingSenderId: '162069967907',
    projectId: 'laptrinhdidongcuoikyv2-8133a',
    storageBucket: 'laptrinhdidongcuoikyv2-8133a.firebasestorage.app',
    iosBundleId: 'com.example.watchstore',
  );

}